<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.10.0 on win32)" generated="20211207 12:42:15.226" rpa="false">
<suite id="s1" name="ApiTest" source="C:\Users\BPetre\Documents\Projects\Eclipse\ApiTest">
<suite id="s1-s1" name="Api Tests" source="C:\Users\BPetre\Documents\Projects\Eclipse\ApiTest\api tests">
<suite id="s1-s1-s1" name="Invalid Tests" source="C:\Users\BPetre\Documents\Projects\Eclipse\ApiTest\api tests\invalid_tests.robot">
<test id="s1-s1-s1-t1" name="Invalid name">
<kw name="Send an invalid dictionary to the API">
<arguments>
<arg>12355</arg>
<arg>${email}</arg>
<arg>${gender}</arg>
<arg>${status}</arg>
</arguments>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>id=500</arg>
<arg>name=${name}</arg>
<arg>email=${email}</arg>
<arg>gender=${gender}</arg>
<arg>status=${status}</arg>
</arguments>
<assign>
<var>${user_dict}</var>
</assign>
<msg timestamp="20211207 12:42:15.409" level="INFO">${user_dict} = {'id': '500', 'name': '12355', 'email': 'AppTest@test.com', 'gender': 'male', 'status': 'active'}</msg>
<status status="PASS" starttime="20211207 12:42:15.408" endtime="20211207 12:42:15.409"></status>
</kw>
<kw name="Invalid Dict Returns Http Error" library="requests_api_app.ApiAPP">
<arguments>
<arg>${user_dict}</arg>
</arguments>
<msg timestamp="20211207 12:42:16.326" level="INFO">C:\Users\BPetre\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gorest.co.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(</msg>
<status status="PASS" starttime="20211207 12:42:15.409" endtime="20211207 12:42:16.327"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:15.408" endtime="20211207 12:42:16.327"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:15.407" endtime="20211207 12:42:16.327" critical="yes"></status>
</test>
<test id="s1-s1-s1-t2" name="Invalid mail">
<kw name="Send an invalid dictionary to the API">
<arguments>
<arg>${name}</arg>
<arg>email</arg>
<arg>${gender}</arg>
<arg>${status}</arg>
</arguments>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>id=500</arg>
<arg>name=${name}</arg>
<arg>email=${email}</arg>
<arg>gender=${gender}</arg>
<arg>status=${status}</arg>
</arguments>
<assign>
<var>${user_dict}</var>
</assign>
<msg timestamp="20211207 12:42:16.330" level="INFO">${user_dict} = {'id': '500', 'name': 'bodi', 'email': 'email', 'gender': 'male', 'status': 'active'}</msg>
<status status="PASS" starttime="20211207 12:42:16.329" endtime="20211207 12:42:16.330"></status>
</kw>
<kw name="Invalid Dict Returns Http Error" library="requests_api_app.ApiAPP">
<arguments>
<arg>${user_dict}</arg>
</arguments>
<msg timestamp="20211207 12:42:16.813" level="INFO">User cannot be added</msg>
<msg timestamp="20211207 12:42:16.814" level="INFO">C:\Users\BPetre\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gorest.co.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(</msg>
<status status="PASS" starttime="20211207 12:42:16.330" endtime="20211207 12:42:16.814"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:16.328" endtime="20211207 12:42:16.815"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:16.328" endtime="20211207 12:42:16.816" critical="yes"></status>
</test>
<test id="s1-s1-s1-t3" name="Invalid gender">
<kw name="Send an invalid dictionary to the API">
<arguments>
<arg>${name}</arg>
<arg>${email}</arg>
<arg>ifdvn</arg>
<arg>${status}</arg>
</arguments>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>id=500</arg>
<arg>name=${name}</arg>
<arg>email=${email}</arg>
<arg>gender=${gender}</arg>
<arg>status=${status}</arg>
</arguments>
<assign>
<var>${user_dict}</var>
</assign>
<msg timestamp="20211207 12:42:16.823" level="INFO">${user_dict} = {'id': '500', 'name': 'bodi', 'email': 'AppTest@test.com', 'gender': 'ifdvn', 'status': 'active'}</msg>
<status status="PASS" starttime="20211207 12:42:16.821" endtime="20211207 12:42:16.824"></status>
</kw>
<kw name="Invalid Dict Returns Http Error" library="requests_api_app.ApiAPP">
<arguments>
<arg>${user_dict}</arg>
</arguments>
<msg timestamp="20211207 12:42:17.340" level="INFO">User cannot be added</msg>
<msg timestamp="20211207 12:42:17.340" level="INFO">C:\Users\BPetre\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gorest.co.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(</msg>
<status status="PASS" starttime="20211207 12:42:16.824" endtime="20211207 12:42:17.341"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:16.819" endtime="20211207 12:42:17.341"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:16.817" endtime="20211207 12:42:17.341" critical="yes"></status>
</test>
<test id="s1-s1-s1-t4" name="Invalid status">
<kw name="Send an invalid dictionary to the API">
<arguments>
<arg>${name}</arg>
<arg>${email}</arg>
<arg>${gender}</arg>
<arg>8328fhh</arg>
</arguments>
<kw name="Create Dictionary" library="BuiltIn">
<doc>Creates and returns a dictionary based on the given ``items``.</doc>
<arguments>
<arg>id=500</arg>
<arg>name=${name}</arg>
<arg>email=${email}</arg>
<arg>gender=${gender}</arg>
<arg>status=${status}</arg>
</arguments>
<assign>
<var>${user_dict}</var>
</assign>
<msg timestamp="20211207 12:42:17.343" level="INFO">${user_dict} = {'id': '500', 'name': 'bodi', 'email': 'AppTest@test.com', 'gender': 'male', 'status': '8328fhh'}</msg>
<status status="PASS" starttime="20211207 12:42:17.343" endtime="20211207 12:42:17.343"></status>
</kw>
<kw name="Invalid Dict Returns Http Error" library="requests_api_app.ApiAPP">
<arguments>
<arg>${user_dict}</arg>
</arguments>
<msg timestamp="20211207 12:42:17.853" level="INFO">User cannot be added</msg>
<msg timestamp="20211207 12:42:17.853" level="INFO">C:\Users\BPetre\AppData\Local\Programs\Python\Python310\Lib\site-packages\urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 'gorest.co.in'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(</msg>
<status status="PASS" starttime="20211207 12:42:17.344" endtime="20211207 12:42:17.853"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:17.342" endtime="20211207 12:42:17.854"></status>
</kw>
<status status="PASS" starttime="20211207 12:42:17.342" endtime="20211207 12:42:17.854" critical="yes"></status>
</test>
<status status="PASS" starttime="20211207 12:42:15.285" endtime="20211207 12:42:17.854"></status>
</suite>
<status status="PASS" starttime="20211207 12:42:15.283" endtime="20211207 12:42:17.857"></status>
</suite>
<status status="PASS" starttime="20211207 12:42:15.263" endtime="20211207 12:42:17.860"></status>
</suite>
<statistics>
<total>
<stat pass="4" fail="0">Critical Tests</stat>
<stat pass="4" fail="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="4" fail="0" id="s1" name="ApiTest">ApiTest</stat>
<stat pass="4" fail="0" id="s1-s1" name="Api Tests">ApiTest.Api Tests</stat>
<stat pass="4" fail="0" id="s1-s1-s1" name="Invalid Tests">ApiTest.Api Tests.Invalid Tests</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
